import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const cleanupScriptPath = path.resolve(process.cwd(), 'scripts/cleanVerificationArtifacts.mjs');
const packageJsonPath = path.resolve(process.cwd(), 'package.json');

describe('verification artifact cleanup', () => {
  it('runs before the full ci script so stale outputs do not survive partial runs', () => {
    const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8')) as { scripts: Record<string, string> };

    expect(packageJson.scripts['clean:verification']).toBe('node scripts/cleanVerificationArtifacts.mjs');
    expect(packageJson.scripts.preci).toBe('npm run clean:verification');
    expect(packageJson.scripts.ci).toContain('npm run test:e2e');
  });

  it('removes generated verification artifacts without deleting local data', () => {
    const tempDir = mkdtempSync(path.join(tmpdir(), 'tinytracker-verification-clean-'));

    try {
      const artifactFiles = [
        path.join('dist', 'server', 'index.js'),
        path.join('dist', 'client', 'assets', 'app.js'),
        path.join('test-results', 'smoke-import-flow-chromium', 'trace.zip'),
        path.join('test-results', 'smoke-import-flow-chromium', 'test-failed-1.png'),
        path.join('playwright-report', 'data', 'trace.zip'),
        path.join('playwright-report', 'index.html')
      ];

      for (const artifactFile of artifactFiles) {
        mkdirSync(path.join(tempDir, path.dirname(artifactFile)), { recursive: true });
        writeFileSync(path.join(tempDir, artifactFile), 'generated by verification');
      }

      mkdirSync(path.join(tempDir, 'data'), { recursive: true });
      writeFileSync(path.join(tempDir, 'data', 'tracker.sqlite'), 'local application data');

      const output = execFileSync(process.execPath, [cleanupScriptPath], {
        cwd: tempDir,
        encoding: 'utf8'
      });

      expect(output).toContain('Cleaned verification artifacts: dist, test-results, playwright-report');
      expect(existsSync(path.join(tempDir, 'dist'))).toBe(false);
      expect(existsSync(path.join(tempDir, 'test-results'))).toBe(false);
      expect(existsSync(path.join(tempDir, 'playwright-report'))).toBe(false);
      expect(existsSync(path.join(tempDir, 'data', 'tracker.sqlite'))).toBe(true);
    } finally {
      rmSync(tempDir, { recursive: true, force: true });
    }
  });
});
