import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const cleanupScriptPath = path.resolve(process.cwd(), 'scripts/cleanVerificationArtifacts.mjs');

describe('verification artifact cleanup', () => {
  it('removes generated verification artifacts without deleting local data', () => {
    const tempDir = mkdtempSync(path.join(tmpdir(), 'tinytracker-verification-clean-'));

    try {
      for (const artifactDir of ['dist', 'test-results', 'playwright-report']) {
        mkdirSync(path.join(tempDir, artifactDir), { recursive: true });
        writeFileSync(path.join(tempDir, artifactDir, 'artifact.txt'), 'generated by verification');
      }

      mkdirSync(path.join(tempDir, 'data'), { recursive: true });
      writeFileSync(path.join(tempDir, 'data', 'tracker.sqlite'), 'local application data');

      const output = execFileSync(process.execPath, [cleanupScriptPath], {
        cwd: tempDir,
        encoding: 'utf8'
      });

      expect(output).toContain('Cleaned verification artifacts: dist, test-results, playwright-report');
      expect(existsSync(path.join(tempDir, 'dist'))).toBe(false);
      expect(existsSync(path.join(tempDir, 'test-results'))).toBe(false);
      expect(existsSync(path.join(tempDir, 'playwright-report'))).toBe(false);
      expect(existsSync(path.join(tempDir, 'data', 'tracker.sqlite'))).toBe(true);
    } finally {
      rmSync(tempDir, { recursive: true, force: true });
    }
  });
});
